# Generated by Skyramp v1.3.17 on 2026-06-13 13:54:17.002768721 +0000 UTC m=+760.507676683
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output albums_sortby_workflow_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_albums-sortby-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    albums_POST_request_body = r'''{
        "albumName": "Zebra-Album"
    }'''
    
    # Execute Request
    albums_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/albums",
        method="POST",
        body=albums_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert albums_POST_response.status_code == 201
    assert skyramp.get_response_value(albums_POST_response, "id") is not None
    assert skyramp.get_response_value(albums_POST_response, "albumName") == "Zebra-Album"
    albums = skyramp.get_response_value(albums_POST_response, "id")

    # Request Body
    albums_POST_1_request_body = r'''{
        "albumName": "Apple-Album"
    }'''
    
    # Execute Request
    albums_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/albums",
        method="POST",
        body=albums_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert albums_POST_1_response.status_code == 201
    assert skyramp.get_response_value(albums_POST_1_response, "id") is not None
    assert skyramp.get_response_value(albums_POST_1_response, "albumName") == "Apple-Album"
    albums_1 = skyramp.get_response_value(albums_POST_1_response, "id")

    # Execute Request
    albums_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/albums",
        method="GET",
        headers=headers,
        query_params={"sortBy": ["name"]}
    )
    # Generated Assertions
    assert albums_GET_response.status_code == 200
    assert skyramp.get_response_value(albums_GET_response, "0.id") is not None
    assert skyramp.get_response_value(albums_GET_response, "0.albumName") is not None

    # Execute Request
    albums_albums_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/albums/{albums}",
        method="DELETE",
        headers=headers,
        path_params={"albums": albums}
    )
    # Generated Assertions
    assert albums_albums_DELETE_response.status_code == 204

    # Execute Request
    albums_albums_DELETE_1_response = client.send_request(
        url=URL_localhost,
        path="/api/albums/{albums}",
        method="DELETE",
        headers=headers,
        path_params={"albums": albums_1}
    )
    # Generated Assertions
    assert albums_albums_DELETE_1_response.status_code == 204


if __name__ == "__main__":
    test_integration()
