# Generated by Skyramp v1.3.17 on 2026-06-13 13:52:33.618119619 +0000 UTC m=+657.123027573
# Command: skyramp generate contract rest http://localhost:2285/api/albums \
# 		--api-schema http://localhost:2285/api/spec.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output albums_get_200_contract_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

# contract test for /api/albums GET
def test_albums_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_albums_GET_response_body = r'''[
        {
            "albumName": "My Test Album",
            "albumThumbnailAssetId": "c1d2e3f4-a5b6-7890-abcd-ef1234567890",
            "albumUsers": [
                {
                    "role": "editor",
                    "user": {
                        "avatarColor": "primary",
                        "email": "user@example.com",
                        "id": "cf383d38-e097-4289-b110-7da0f687108a",
                        "name": "Test User",
                        "profileChangedAt": "2026-06-13T13:52:33Z",
                        "profileImagePath": "profile.jpg"
                    }
                }
            ],
            "assetCount": 0,
            "contributorCounts": [
                {
                    "assetCount": 0,
                    "userId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                }
            ],
            "createdAt": "2026-06-13T13:52:33Z",
            "description": "Album Description",
            "endDate": "2026-06-13T13:52:33Z",
            "hasSharedLink": false,
            "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            "isActivityEnabled": false,
            "lastModifiedAssetTimestamp": "2026-06-13T13:52:33Z",
            "order": "asc",
            "shared": false,
            "startDate": "2026-06-13T13:52:33Z",
            "updatedAt": "2026-06-13T13:52:33Z"
        }
    ]'''

    # Execute Request
    albums_GET_response = client.send_request(
        url=URL,
        path="/api/albums",
        method="GET",
        headers=headers,
        query_params={
            "assetId": None,
            "id": None,
            "isOwned": None,
            "isShared": None,
            "name": None,
            "sortBy": None
        }
    )

    # Generated Assertions
    assert albums_GET_response.status_code == 200
    assert skyramp.check_schema(albums_GET_response, expected_albums_GET_response_body)


if __name__ == "__main__":
    test_albums_get()
