# Generated by Skyramp v1.3.17 on 2026-06-13 13:54:05.055106432 +0000 UTC m=+748.560014391
# Command: skyramp generate contract rest http://localhost:2285/api/albums \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output albums_get_sortby_invalid_400_contract_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--query-params sortBy=invalid \
# 		--response-status-code 400 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

# contract test for /api/albums GET
def test_albums_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    albums_GET_response = client.send_request(
        url=URL,
        path="/api/albums",
        method="GET",
        headers=headers,
        query_params={"sortBy": "invalid"}
    )

    # Generated Assertions
    assert albums_GET_response.status_code == 400


if __name__ == "__main__":
    test_albums_get()
