# Generated by Skyramp v1.3.17 on 2026-06-13 13:49:23.001988293 +0000 UTC m=+434.580525466
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output assets_unique_constraint_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_assets-unique-constraint.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    assets_POST_request_body = r'''{
        "deviceAssetId": "test-device-asset-unique-001",
        "deviceId": "test-device-001",
        "fileCreatedAt": "2024-01-01T00:00:00.000Z",
        "fileModifiedAt": "2024-01-01T00:00:00.000Z"
    }'''
    
    # Execute Request
    assets_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/assets",
        method="POST",
        body=assets_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert assets_POST_response.status_code == 201
    assert skyramp.get_response_value(assets_POST_response, "id") is not None

    # Request Body
    assets_POST_1_request_body = r'''{
        "deviceAssetId": "test-device-asset-unique-001",
        "deviceId": "test-device-001",
        "fileCreatedAt": "2024-01-01T00:00:00.000Z",
        "fileModifiedAt": "2024-01-01T00:00:00.000Z"
    }'''
    
    # Execute Request
    assets_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/assets",
        method="POST",
        body=assets_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert assets_POST_1_response.status_code == 409


if __name__ == "__main__":
    test_integration()
