# Generated by Skyramp v1.3.17 on 2026-06-13 13:49:25.050875097 +0000 UTC m=+436.629412250
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output bulk_upload_check_unique_constraint_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_bulk-upload-check-unique-constraint.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    bulk_upload_check_POST_request_body = r'''{
        "assets": [
            {
                "checksum": "abc123def456abc123def456abc123def456abc1",
                "id": "test-device-asset-bulk-001"
            }
        ]
    }'''
    
    # Execute Request
    bulk_upload_check_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/assets/bulk-upload-check",
        method="POST",
        body=bulk_upload_check_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert bulk_upload_check_POST_response.status_code == 200
    assert skyramp.get_response_value(bulk_upload_check_POST_response, "results.0.id") is not None
    assert skyramp.get_response_value(bulk_upload_check_POST_response, "results.0.action") is not None

    # Request Body
    bulk_upload_check_POST_1_request_body = r'''{
        "assets": [
            {
                "checksum": "abc123def456abc123def456abc123def456abc1",
                "id": "test-device-asset-bulk-001"
            }
        ]
    }'''
    
    # Execute Request
    bulk_upload_check_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/assets/bulk-upload-check",
        method="POST",
        body=bulk_upload_check_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert bulk_upload_check_POST_1_response.status_code == 200


if __name__ == "__main__":
    test_integration()
