# Generated by Skyramp v1.3.17 on 2026-06-13 13:49:21.460463375 +0000 UTC m=+433.039000538
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output id_unique_constraint_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_id-unique-constraint.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    activities_POST_request_body = r'''{
        "albumId": "00000000-0000-4000-a000-000000000001",
        "assetId": "00000000-0000-4000-a000-000000000002",
        "type": "like"
    }'''
    
    # Execute Request
    activities_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/activities",
        method="POST",
        body=activities_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert activities_POST_response.status_code == 201
    assert skyramp.get_response_value(activities_POST_response, "id") is not None
    assert skyramp.get_response_value(activities_POST_response, "type") == "like"

    # Request Body
    activities_POST_1_request_body = r'''{
        "albumId": "00000000-0000-4000-a000-000000000001",
        "assetId": "00000000-0000-4000-a000-000000000002",
        "type": "like"
    }'''
    
    # Execute Request
    activities_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/activities",
        method="POST",
        body=activities_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert activities_POST_1_response.status_code == 409


if __name__ == "__main__":
    test_integration()
