# Generated by Skyramp v1.3.17 on 2026-06-13 13:47:31.36059374 +0000 UTC m=+300.257473198
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output server_health_integration_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/immich-testb/immich-testb/tests/skyramp/scenario_server-health-check.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    health_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/server/health",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert health_GET_response.status_code == 200
    assert skyramp.get_response_value(health_GET_response, "status") is not None
    assert skyramp.get_response_value(health_GET_response, "status") == "ok"
    assert skyramp.get_response_value(health_GET_response, "uptime") is not None
    assert skyramp.get_response_value(health_GET_response, "uptime") >= 0


if __name__ == "__main__":
    test_integration()
