# Generated by Skyramp v1.3.17 on 2026-06-13 13:47:28.354418184 +0000 UTC m=+297.251297642
# Command: skyramp generate contract rest http://localhost:2285/api/server/health \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output server_health_unauth_contract_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import os
import skyramp


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

# contract test for /api/server/health GET
def test_server_health_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # No auth headers — intentionally unauthenticated to verify 401 boundary
    headers = {}

    # Execute Request
    server_health_GET_response = client.send_request(
        url=URL,
        path="/api/server/health",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert server_health_GET_response.status_code == 401


if __name__ == "__main__":
    test_server_health_get()
