# Generated by Skyramp v1.3.17 on 2026-06-13 13:47:12.693488259 +0000 UTC m=+281.590367747
# Command: skyramp generate contract rest http://localhost:2285/api/server/health \
# 		--api-schema http://localhost:2285/api/spec.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output server_health_contract_test.py \
# 		--output-dir /home/runner/work/immich-testb/immich-testb/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

# contract test for /api/server/health GET
def test_health_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_health_GET_response_body = r'''{
        "status": "ok",
        "uptime": 42.5
    }'''

    # Execute Request
    health_GET_response = client.send_request(
        url=URL,
        path="/api/server/health",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert health_GET_response.status_code == 200
    assert skyramp.check_schema(health_GET_response, expected_health_GET_response_body)
    assert skyramp.get_response_value(health_GET_response, "status") is not None
    assert skyramp.get_response_value(health_GET_response, "uptime") is not None
    assert skyramp.get_response_value(health_GET_response, "status") == "ok"
    assert skyramp.get_response_value(health_GET_response, "uptime") >= 0


if __name__ == "__main__":
    test_health_get()
